CREATE TABLE USERS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CEDULA      VARCHAR2(20)  NOT NULL,
    NOMBRE      VARCHAR2(100) NOT NULL,
    APELLIDO    VARCHAR2(100) NOT NULL,
    CELULAR     VARCHAR2(15)  NOT NULL,
    EMAIL       VARCHAR2(150) NOT NULL,
    PASSWORD    VARCHAR2(255) NOT NULL,
    ROLE        VARCHAR2(20)  DEFAULT 'USER' NOT NULL,
    BALANCE     NUMBER(15,2)  DEFAULT 0.00 NOT NULL,
    ACTIVO      CHAR(1)       DEFAULT 'A' NOT NULL,
    CREATED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT UQ_USERS_CEDULA UNIQUE (CEDULA),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_USERS_ACTIVO CHECK (ACTIVO IN ('A', 'I')),
    CONSTRAINT CHK_USERS_BALANCE CHECK (BALANCE >= 0)
);