-- =============================================
-- SCRIPT COMPLETO PARA ORACLE (BANK APP con roles)
-- =============================================

-- 1. TABLA DE USUARIOS (incluye columna USER_ROLE)
CREATE TABLE BANK_USERS (
    USER_ID VARCHAR2(36) PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    ACCOUNT_NUMBER VARCHAR2(20) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    BALANCE NUMBER(15,2) DEFAULT 0.00 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE CHAR(1) DEFAULT '1' CHECK (IS_ACTIVE IN ('0','1')),
    USER_ROLE VARCHAR2(10) DEFAULT 'USER' NOT NULL CHECK (USER_ROLE IN ('ADMIN', 'USER'))
);

-- 2. TABLA DE TRANSACCIONES
CREATE TABLE BANK_TRANSACTIONS (
    TRANSACTION_ID VARCHAR2(36) PRIMARY KEY,
    FROM_USER_ID VARCHAR2(36) NOT NULL,
    TO_USER_ID VARCHAR2(36) NOT NULL,
    AMOUNT NUMBER(15,2) NOT NULL,
    CONCEPT VARCHAR2(255),
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING','COMPLETED','FAILED')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TRANS_FROM FOREIGN KEY (FROM_USER_ID) REFERENCES BANK_USERS(USER_ID),
    CONSTRAINT FK_TRANS_TO FOREIGN KEY (TO_USER_ID) REFERENCES BANK_USERS(USER_ID)
);

-- 3. ÍNDICES PARA RENDIMIENTO
CREATE INDEX IDX_TRANSACTIONS_FROM ON BANK_TRANSACTIONS(FROM_USER_ID);
CREATE INDEX IDX_TRANSACTIONS_TO ON BANK_TRANSACTIONS(TO_USER_ID);
CREATE INDEX IDX_TRANSACTIONS_DATE ON BANK_TRANSACTIONS(CREATED_AT DESC);

-- 4. DATOS DE PRUEBA (la contraseña "admin123" se encriptará con BCrypt desde Java)
-- Por ahora insertamos un usuario ADMIN con un hash genérico, pero luego se actualizará desde el DataInitializer
INSERT INTO BANK_USERS (USER_ID, FULL_NAME, EMAIL, ACCOUNT_NUMBER, PASSWORD_HASH, BALANCE, USER_ROLE)
VALUES ('11111111-1111-1111-1111-111111111111', 'Admin Principal', 'admin@bank.com', 'ES00', '$2a$10$dummyHashQueDebesReemplazar', 10000.00, 'ADMIN');

-- Usuario normal de prueba
INSERT INTO BANK_USERS (USER_ID, FULL_NAME, EMAIL, ACCOUNT_NUMBER, PASSWORD_HASH, BALANCE, USER_ROLE)
VALUES ('22222222-2222-2222-2222-222222222222', 'Cliente Normal', 'user@bank.com', 'ES01', '$2a$10$dummyHashQueDebesReemplazar', 2500.00, 'USER');

COMMIT;
