server.port=8080
server.address=0.0.0.0
spring.application.name=bank-backend


# CONFIGURACION DE CONEXION
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=C##GS04_BANK_DB
spring.datasource.password=BancoSeguro2026

# CONFIGURACION JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ESTRATEGIAS DE NOMBRAMIENTO
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=false