server.port=8080
spring.application.name=bank-backend

# CONFIGURACIÓN DE CONEXIÓN A ORACLE DB (Actualizado con tu usuario nuevo)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=c##gs04_bank_db
spring.datasource.password=BancoSeguro2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# Cambiamos 'validate' por 'update' para que Spring Boot cree las tablas en tu usuario si falta alguna
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.web=INFO