server.port=8080
spring.application.name=bank-backend

# Oracle Connection - CAMBIAR SEGÚN TU INSTALACIÓN
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=BANKAPP
spring.datasource.password=TuPasswordSeguro123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect

# Logging
logging.level.org.springframework.web=DEBUG
